---
title: "her2_pr_er_test"
output: pdf_document
date: "2023-07-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("GenomicDataCommons")
library(GenomicDataCommons)
library(maftools)
library(data.table)
library(TCGAbiolinks)
```

```{r}
query <- GDCquery(
    project = "TCGA-BRCA", 
    data.category = "Clinical",
    data.type = "Clinical Supplement", 
    data.format = "BCR Biotab"
)
GDCdownload(query)
clinical.BCRtab.all <- GDCprepare(query)
clinical_data <- clinical.BCRtab.all$clinical_patient_brca

clinical_subset <- c("bcr_patient_barcode","pr_status_by_ihc","her2_status_by_ihc","er_status_by_ihc")
categorical_cols <- c("tissue_source_site",
                    "icd_10",
                    "race",
                    "ethnicity")

binary_cols <- c("gender",
                "vital_status")

numerical_cols <- c("age_at_diagnosis")

target_groups <- c("ajcc_tumor_pathologic_pt")
clinical_subset_data <- clinical_data[,c(clinical_subset, categorical_cols, binary_cols, target_groups, numerical_cols)]
```

```{r}
GenomicDataCommons::status()

cases_by_project <- cases() %>%
  facet("project.project_id") %>%
  aggregations()
head(cases_by_project)

maf.files = files() %>%
    filter(~ cases.project.project_id == 'TCGA-BRCA' &
        data_type == 'Masked Somatic Mutation' &
        data_format == "MAF"
    ) %>%
    response_all()

View(maf.files)
```

```{r}
uid <- ids(maf.files)

maffile = gdcdata(uid)
```

```{r}
# Create a new subdirectory
subdir <- "gene_level_data"
if (!dir.exists(file.path(getwd(), subdir))) {
  dir.create(file.path(getwd(), subdir))
}

# Move downloaded files to the subdirectory
for (file in maffile) {
  file.copy(file, file.path(getwd(), subdir, basename(file)))
}
```

```{r}
# Get list of .maf.gz files in the subdirectory
gz_files <- list.files(path = subdir, pattern = "*.maf.gz")

# Initialize an empty list to store the MAF objects
maf_list <- list()

# Initialize a counter for the "No non-synonymous mutations found" errors
error_count <- 0

# Initialize an empty data.table for storing MATH scores
math_scores <- data.table()

# Initialize an empty data frame for the count matrix
count_matrix <- data.frame()

# Process each .maf.gz file
for (gz_file in gz_files) {
  # Decompress the .maf.gz file
  command <- paste("gzip -d", file.path(subdir, gz_file))
  system(command)

  # Get the .maf file name
  maf_file <- sub(".gz$", "", gz_file)

  # Try to read the .maf file into a MAF object
  tryCatch({
    maf <- maftools::read.maf(maf = file.path(subdir, maf_file))

    # Calculate the MATH score
    math_score <- maftools::math.score(maf)
  
    # Merge the MATH score into the math_scores data.table
    math_scores <- rbind(math_scores, math_score)

    # Add the MAF object to the list
    maf_list[[length(maf_list) + 1]] <- maf
  },
  error = function(e) {
      # If it is, increment the error counter
      error_count = error_count + 1
    })

  # Delete the .maf file
  file.remove(file.path(subdir, maf_file))
}

# Combine the MAF objects
merged_maf <- maftools::merge_mafs(maf_list)

# Print the number of "No non-synonymous mutations found" errors
print(paste("Number of 'Number of files with errors:", error_count))
```


```{r}
# Calculate the MATH score
math_score_merged <- maftools::math.score(merged_maf)
```

```{r}
# Write the combined MAF object to a file
maftools::write.mafSummary(maf = merged_maf, basename = 'gene_level_data/merged')

# Get list of .txt files in the subdirectory
txt_files <- list.files(path = subdir, pattern = "\\.txt$")

# Process each .txt file
for (txt_file in txt_files) {
  # Read the .txt file into a data frame
  data <- read.delim(file.path(subdir, txt_file))

  # Write the data frame to a .csv file
  write.csv(data, file = file.path(subdir, sub("\\.txt$", ".csv", txt_file)), row.names = FALSE)
}

# Read the merged_sampleSummary.csv into a data frame
merged_sampleSummary <- read.csv("gene_level_data/merged_sampleSummary.csv")

# Merge the MATH scores into the merged_sampleSummary data frame
merged_sampleSummary <- merge(merged_sampleSummary, math_scores, by = "Tumor_Sample_Barcode")

# Write the merged_sampleSummary data frame with the MATH scores back to a .csv file
write.csv(merged_sampleSummary, "gene_level_data/merged_sampleSummary_with_MATH.csv")
```


```{r}
# 1. Define a function to extract 'bcr_patient_barcode' from 'Tumor_Sample_Barcode'
extract_bcr_patient_barcode <- function(tumor_sample_barcode) {
    # Split the string by "-"
    split_string <- strsplit(tumor_sample_barcode, "-")[[1]]
    # Concatenate the parts before the third dash
    paste(split_string[1:3], collapse = "-")
}

# 2. Apply the function to 'Tumor_Sample_Barcode' column in 'merged_sampleSummary'
merged_sampleSummary$bcr_patient_barcode <- sapply(merged_sampleSummary$Tumor_Sample_Barcode, extract_bcr_patient_barcode)

# 3. Now you can merge 'clinical' and 'merged_sampleSummary' based on 'bcr_patient_barcode'
non_bin_merged_df <- merge(clinical_subset_data, merged_sampleSummary, by="bcr_patient_barcode")
```

```{r}
# Generate the count matrix of mutations
mut_count_matrix <- maftools::mutCountMatrix(merged_maf)

# Reformat the count matrix to have samples as rows,
# genes as columns, and binary values
# reformatted_count_matrix = copy(as.data.frame(t(count_matrix)))

# print(reformatted_count_matrix)
# print(class(reformatted_count_matrix))

write.csv(as.data.frame(t(mut_count_matrix)),
                "gene_level_data/reformatted_count_matrix.csv",  row.names = TRUE)

reformatted_count_matrix <- read.csv("gene_level_data/reformatted_count_matrix.csv")
tumor_barcodes <- reformatted_count_matrix$X

reformatted_count_matrix <- as.data.frame(
            lapply(reformatted_count_matrix, function(x) ifelse(x > 0, 1, 0)))

reformatted_count_matrix$Tumor_Sample_Barcode <- tumor_barcodes

reformatted_count_matrix <- subset(reformatted_count_matrix, select = -X)

pre_merged_df <- merge(reformatted_count_matrix,
                    merged_sampleSummary,
                    by = "Tumor_Sample_Barcode", all = TRUE)

merged_df <- merge(x = pre_merged_df,
                   y = non_bin_merged_df,
                   by.x = "Tumor_Sample_Barcode",
                   by.y = "Tumor_Sample_Barcode")

# Drop rows with NaN values
merged_df <- merged_df[complete.cases(merged_df), ]

# Write the merged_sampleSummary data frame with the MATH scores
# back to a .csv file
write.csv(merged_df, "gene_level_data/merged.csv")
```